name: Version & Publish

on:
  workflow_dispatch:
    inputs:
      newversion:
        description: 'Semantic Version Bump Type (major minor patch)'
        required: true

env:
  node_version: 14

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Initialize Submodules
        run: git submodule update --init
        
      - name: Setup Git
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
      
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ env.node_version }}
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install Packages
        run: npm i
        
      - name: Build
        run: npm run build

#      - name: Test
#        run: npm run test
      
      - name: Bump Version ${{ github.event.inputs.newversion }}
        run: npm version ${{ github.event.inputs.newversion }}
  
      - name: Create Branch release-${{ github.event.inputs.newversion }}
        run: git checkout -b release-$(npm run version --silent)
      
#      - name: Tag Version
#        run: git tag -a v$(npm run version --silent) -m "Version $(npm run version --silent)"
        
      - name: Create Changelog
        run: |
          npm run changelog
          git add CHANGELOG.md
          
      - name: Commit Changes
        run: git commit -m "Bumped Version to $(npm run version --silent)"
        
      - name: Publish Version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm publish
          
          
      - name: Publish Version
        uses: pascalgn/npm-publish-action@06e0830ea83eea10ed4a62654eeaedafb8bf50fc
        with:
          tag_name: "v%s"
          tag_message: "v%s"
          commit_pattern: "^Release (\\S+)"
          workspace: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
