name: Version & Publish

on:
  workflow_dispatch:
    inputs:
      newversion:
        description: 'Semantic Version Bump Type (major minor patch)'
        required: true

env:
  node_version: 14

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Extract Branch Name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      
      - name: Checkout ${{ steps.extract_branch.outputs.branch }}
        run: git checkout ${{ steps.extract_branch.outputs.branch }}
        
      - name: Initialize Submodules
        run: git submodule update --init
        
      - name: Setup Git
        run: |
          git config --global user.email "${{ secrets.GIT_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
      
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ env.node_version }}
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install Packages
        run: npm i
        
      - name: Build
        run: npm run build

#      - name: Test
#        run: npm run test
      
      - name: Bump Version ${{ github.event.inputs.newversion }}
        run: npm version ${{ github.event.inputs.newversion }}
        
      - name: Extract Bump Version
        shell: bash
        run: echo "##[set-output name=version;]$(echo $(npm run version --silent))"
        id: extract_bump_version
  
      - name: Create Branch release-${{ steps.extract_bump_version.outputs.version }}
        run: git checkout -b release-${{ steps.extract_bump_version.outputs.version }}
        
      - name: Create Changelog
        run: |
          npm run changelog
          git add CHANGELOG.md

      - name: Commit Changes
        run: git commit -m "Bumped Version to $(npm run version --silent)"

      - name: Push Branch & Merge
        run: |
          git push --set-upstream origin release-${{ steps.extract_bump_version.outputs.version }}
          git checkout ${{ steps.extract_branch.outputs.branch }}
          git merge release-${{ steps.extract_bump_version.outputs.version }}
          git push
          
      - name: Publish Version
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm publish
